<?php

namespace Les\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Les\DataBundle\Entity\Restaurants;

/**
 * RestaurantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantsRepository extends EntityRepository
{


}
