virtual_market_index:
    pattern:   /
    defaults:  { _controller: LesVirtualMarketBundle:VirtualMarket:index}


virtual_market_focus:
    pattern:   /focus/{id}
    defaults:  { _controller: LesVirtualMarketBundle:VirtualMarket:focus}
