
#  ---------------  COUVERTS ROUTING --------------
lescouverts:
    resource: "@LesCouvertsBundle/Resources/config/routing.yml"
    prefix:   /


resto_admin:
    resource: "@LesRestaurantBundle/Resources/config/routing.yml"
    prefix:   /restaurant_admin

virtual_market:
    resource: "@LesVirtualMarketBundle/Resources/config/routing.yml"
    prefix:   /virutal_market


shop_admin:
    resource: "@LesShopBundle/Resources/config/routing.yml"
    prefix:   /shop_admin

#  ---------------  END COUVERTS ROUTING --------------


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile



hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /secure_area/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /secure_area/connect

hwi_oauth_login:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /secure_area/connect

hwi_github_login:
    pattern: /secure_area/login/check-github
    defaults: { _controller: LesCouvertsBundle:Couverts:index }

hwi_facebook_login:
    pattern: /secure_area/login/check-facebook
    defaults: { _controller: LesCouvertsBundle:Couverts:index }

hwi_google_login:
    pattern: /secure_area/login/check-google
    defaults: { _controller: LesCouvertsBundle:Couverts:index }

