security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CLIENT:      ROLE_USER
        ROLE_RESTO:       ROLE_CLIENT
        ROLE_ADMIN:       [ ROLE_USER, ROLE_CLIENT, ROLE_RESTO ]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
                    pattern: ^/
                    form_login:
                        provider: fos_userbundle
                        csrf_provider: form.csrf_provider
                        check_path: /login_check
                    logout:
                        path: fos_user_security_logout
                    anonymous:    true

        secure_area:
                    pattern: ^/secure_area

                    oauth:
                            failure_path: /secure_area/connect
                            login_path: /secure_area/connect
                            check_path: /secure_area/connect
                            provider: fos_userbundle
                            resource_owners:
                                  github:           "/secure_area/login/check-github"
                                  facebook:         "/secure_area/login/check-facebook"
                            oauth_user_provider:
                                  service: hwi_oauth.user.provider.fosub_bridge

                    anonymous:    true
                    logout:
                             path:           /secure_area/logout
                             target:         / #where to go after logout



    access_control:
         - { path: ^/booking, role: ROLE_CLIENT }
         - { path: ^/party_calendar, role: ROLE_CLIENT }
         - { path: ^/restaurant_admin, role: ROLE_RESTO }

         - { path: ^/secure_area/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/secure_area/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/secure_area, role: ROLE_USER }
