parameters:
#    les_restaurant.example.class: Les\RestaurantBundle\Example

services:
#    les_restaurant.example:
#        class: %les_restaurant.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
