parameters:
#    les_user.example.class: Les\UserBundle\Example

services:
#    les_user.example:
#        class: %les_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
