parameters:
#    les_couverts.example.class: Les\CouvertsBundle\Example

services:
#    les_couverts.example:
#        class: %les_couverts.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
